export const CELL = "CELL"
export const CLUSTER = "CLUSTER"
export const MATRIX = "MATRIX"
export const DELAY = "DELAY"
export const PATTERN = "PATTERN"
export const CELLSIZE = "CELLSIZE"
export const RESET = "RESET"
